from typing import TypedDict


class Timeframe(TypedDict, total=False):
    year: str | None
    quarter: str | None
    month: str | None


class AssetState(TypedDict, total=False):
    user_query: str
    request_type: str
    properties: list[str]
    timeframe: Timeframe
    extract_attempts: int
    raw_data: dict
    result: str
    error: str
    # SQL pipeline fields (Phase 2+)
    sql_query: str      # DuckDB SQL generated by plan_sql_node
    sql_result: str     # JSON-serialised query result from execute_node
    sql_error: str      # validation or execution error fed back to plan_sql_node
    plan_attempts: int  # number of SQL generation + execution cycles
